Generate pdf template
s1seven/schema-tools pull request #14
Opened 2020-11-10 09:36 UTC by MiZiet

2020-11-10 10:27 UTC, getlarge requested changes
Looks pretty good! 
I will give it a try a bit later. In the meantime could you also remove yarn.lock ?
In this project i'm using package-lock.json files with lerna.

2020-11-10 10:27 UTC, getlarge commented on packages/generate-EN10168-pdf-template/package.json
> +  },
Could you inspire from the other packages for running the tests ?

Also could you add a script to trigger `update-version.ts` in order to have a fresh `schemaTypes.ts`

2020-11-10 10:27 UTC, getlarge commented on packages/generate-EN10168-pdf-template/test/renderingCommTrans.ts
> +const certificate = require('./testingCertificate.json');
Please use the resources in fixtures folder, v0.0.2 is the version you build the pdf-template generator for.

2020-11-10 10:27 UTC, getlarge commented on packages/generate-EN10168-pdf-template/utils/DE.json
> +    "A01": "Herstellerwerk",
Please remove those translations

2020-11-10 10:27 UTC, getlarge commented on packages/generate-EN10168-pdf-template/utils/translate.ts
> +}
Here the idea is load the translations from the schema repository.

Please have a look at this function in generate-html module
```ts
const getTranslations = async (certificateLanguages: string[], schemaConfig: SchemaConfig): Promise<Translations> => {
  const translationsArray = await Promise.all(
    certificateLanguages.map(async (lang) => {
      const filePath = getRefSchemaUrl(schemaConfig, `${lang}.json`).href;
      return { [lang]: (await loadExternalFile(filePath, 'json')) as any };
    }),
  );

  return translationsArray.reduce((acc, translation) => {
    const [key] = Object.keys(translation);
    acc[key] = translation[key];
    return acc;
  }, {});
};
```

2020-11-10 10:40 UTC, krzysztof-jelski commented on packages/generate-EN10168-pdf-template/utils/createExample.ts
> +// const file = fs.createWriteStream('fonts2/Lato-Regular.ttf');
Remove the comment

2020-11-10 11:05 UTC, krzysztof-jelski commented on packages/generate-EN10168-pdf-template/test/renderingSuppInform.ts
> +    const supplementarInforamtion = supplementaryInformation(suppInfo, i18n, 4);
```suggestion
    const supplementarInformation = supplementaryInformation(suppInfo, i18n, 4);
```

2020-11-10 11:13 UTC, krzysztof-jelski commented on packages/generate-EN10168-pdf-template/src/lib/supplementaryInformation.ts
> +const createBrackets = (amount: number) => [...Array(amount).fill({})];
Maybe we could name it after the goal/result. `createEmptyObjects`?

2020-11-10 11:18 UTC, krzysztof-jelski commented on packages/generate-EN10168-pdf-template/src/lib/createProductDescription.ts
> +  const content = Object.keys(productDescription).filter(element => !contentToOmit.includes(element)).map(element =>
That's almost identical to how we generate `content` in `commercialTransaction`. Perhaps worth extracting a function.

2020-11-10 11:19 UTC, krzysztof-jelski commented on packages/generate-EN10168-pdf-template/src/lib/createTransactionParties.ts
> +  if (arr.length === 3){
The `3` in this file is worth extracting to a well-named constant.

2020-11-16 15:42 UTC, getlarge approved these changes

2020-11-16 15:44 UTC, merged