fix: add localization for Value, Minimum and Maximum in inspections for generatePdf
s1seven/schema-tools pull request #144
Opened 2022-05-13 12:35 UTC by eamon0989

# Description

Inspection values were not localizing correctly for the `Value`, `Minimum`, and `Maximum` properties if the type was a `string` instead of a `number`. This is due to a check in `localizeNumber` that checks if the value is of type `number`, otherwise returning the original value.

```TypeScript
else if (format === 'Number' && typeof value === 'number') {
    return localizeNumber(value, locales);
  }
```

My code localizes the number before it is passed to `computeTextStyle`, ensuring that it is correctly localized even if it is a `string`.

Fixes #143 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2022-05-16 15:28 UTC, getlarge requested changes

2022-05-17 05:33 UTC, eamon0989 commented on packages/generate-coa-pdf-template/test/builders.spec.ts
> +  });
Good idea 👍🏼

2022-05-17 05:38 UTC, eamon0989 commented on packages/generate-coa-pdf-template/src/generateContent.ts
> +      const localizedNumber = localizeNumber(inspection[name], i18n.languages);
Thanks for the tip 👍🏼

2022-05-17 19:18 UTC, getlarge approved these changes

2022-05-17 19:18 UTC, merged